function [flag] = qfCYG(quality_flags)
%quality_flag: quality_flags field from CYGNSS netcdf (decimal)
%flag: 1 - overall bad quality  
%      0 - overall good quality 
bit = dec2bin(quality_flags,29);
bit = fliplr(bit);

if(bit(1)=='1') %overall quality
    flag = 1;
else
    flag = 0;
end

%{
disp(bit)
if(bit(1)=='1') %overall quality
    disp('poor_overall_quality: the logical OR of large_sc_attitude_err, black_body_ddm, ddmi_reconfigured, spacewire_crc_invalid, ddm_is_test_pattern, channel_idle, low_confidence_ddm_noise_floor, sp_over_land, sp_very_near_land, large_step_noise_floor, large_step_lna_temp, direct_signal_in_ddm, low_confidence_gps_eirp_estimate, rfi_detected, brcs_ddm_sp_bin_delay_error,  brcs_sp_bin_dopp_error, gps_pvt_sp3_error, brcs_lut_range_error, ant_data_lut_range_error, bb_framing_error, fsw_comp_shift_error.')
end

if(bit(2)=='1') 
    disp('s_band_powered_up: S-band transmitter is powered up.')
end

if(bit(3)=='1') 
    disp('small_sc_attitude_err: Set if the absolute value of the spacecraft roll is between 1 and 30 degrees, the pitch is between 1 and 10 degrees, or the yaw is between 1 and 5 degrees.')
end

if(bit(4)=='1') 
    disp('large_sc_attitude_err: the absolute value of the spacecraft roll is greater than or equal to 30 degrees, the pitch is greater than or equal to 10 degrees, or the yaw is greater than or equal to 5 degrees.')
end

if(bit(5)=='1') 
    disp('black_body_ddm: the black body load was selected during the DDM sampling period.')
end

if(bit(6)=='1') 
    disp('ddmi_reconfigured: the DDMI was reconfigured during the DDM sampling period.')
end

if(bit(7)=='1')
    disp('spacewire_crc_invalid: the DDM CRC transmitted from the DDMI to the spacecraft computer was not valid.')
end

if(bit(8)=='1') 
    disp('ddm_is_test_pattern: the DDM is a test pattern generated by the DDMI.')
end

if(bit(9)=='1') 
    disp('channel_idle: this reflectometry channel was not tracking a PRN.')
end

if(bit(10)=='1') 
    disp('low_confidence_ddm_noise_floor: the difference between this DDM noise floor and the previous DDM noise floor is greater than 10%.')
end

if(bit(11)=='1')
    disp('sp_over_land: the specular point is over land.')
end

if(bit(12)=='1') 
    disp('sp_very_near_land: the specular point is within 25 km of land.')
end

if(bit(13)=='1') 
    disp('sp_near_land: the specular point is within 50 km of land.')
end

if(bit(15)=='1') 
    disp('large_step_lna_temp: the LNA temperature rate of change is greater than 1 degree C per minute.')
end

if(bit(16)=='1') 
    disp('direct_signal_in_ddm:  absolute value of the difference between direct signal code phase and the DDM signal code phase is less than or equal to four.')
end

if(bit(17)=='1') 
    disp('low_confidence_gps_eirp_estimate: there is low confidence in the GPS effective isotropic radiated power estimate.')
end

if(bit(18)=='1') 
    disp('rfi_detected: the kurtosis of the DDM noise floor deviates from pure Gaussian (3.0) by more than 1.0.')
end

if(bit(19)=='1') 
    disp('brcs_ddm_sp_bin_delay_error. the calculated specular point bin zero-based delay row is less than 6 or greater than 10.')
end

if(bit(20)=='1') 
    disp('brcs_ddm_sp_bin_dopp_error. the calculated specular point bin zero-based Doppler column is less than 4 or greater than 6.')
end

if(bit(21)=='1') 
    disp('neg_brcs_value_used_for_nbrcs. any bin in the 3 x 5 brcs area used to calculate ddm_nbrcs has a negative value.')
end

if(bit(22)=='1') 
    disp('gps_pvt_sp3_error. Cannot calculate GPS SV position/velocity/time from SP3 file.')
end

if(bit(23)=='1') 
    disp('sp_non_existent_error. Specular point does not exist.')
end

if(bit(24)=='1') 
    disp('brcs_lut_range_error. Unable to index into BRCS uncertainty lookup table.')
end

if(bit(25)=='1') 
    disp('ant_data_lut_range_error. Unable to index into antenna data lookup table.')
end

if(bit(26)=='1') 
    disp('bb_framing_error. Insufficient black body data for calibration.')
end

if(bit(27)=='1') 
    disp('fsw_comp_shift_error. Flight software telemetry encoding error  of the fsw_comp_delay_shift and fsw_comp_dopp_shift variables. Corrected in FSW version 4.5.')
end

if(bit(28)=='1') 
    disp('low_quality_gps_ant_knowledge: The directional gain pattern of the GPS transmit antenna, and hence the value of its gain in the direction of the specular point, is less well known for block II-F GPS satellites.')
end

if(bit(29)=='1') 
    disp('sc_altitude_out_of_nominal_range: The spacecraft''s altitude is out of nominal altitude range. Nominal altitude is defined as between 490 km to 550 km.')
end
%}

end

